### ISSUE TITLE
[Feature] Option to turn off specific flat checks

### ISSUE THREAD

**Issue by ChasarooniZ** [Latharne/pf2-flat-check#4]
Hi, I'd like certain checks to be handled by other modules ideally if possible, IE perception by the perception module

**Comment by Latharne** [comment]
Hi, i like this idea. I will implement it soon.

**Comment by Latharne** [comment]
I have added three checkboxes to handle the main conditions (concealed variants, grabbed and hidden variants). As far as i can see, i would have to refactor the functions to offer more granular options
